(function () {
  const IMAGE_MIME_BY_EXT = { jpg: "image/jpeg", jpeg: "image/jpeg", png: "image/png", webp: "image/webp", gif: "image/gif", bmp: "image/bmp", tif: "image/tiff", tiff: "image/tiff" };
  const fs = window.require ? window.require("fs") : null;
  const http = window.require ? window.require("http") : null;
  const state = { selectedItem: null, resultItem: null, previewSrc: "", target: "gpt", lang: "zh", busy: false, status: "等待选择图片", error: "", selectionKey: "", selectionTimer: null, warmupTimer: null, initialized: false };
  const $ = (selector) => document.querySelector(selector);

  function mimeFromPath(filePath) { const ext = String(filePath || "").split(".").pop()?.toLowerCase() || "png"; return IMAGE_MIME_BY_EXT[ext] || "image/png"; }
  function selectedItemKey(item) { return item ? String(item.id || item.filePath || item.fileURL || item.thumbnailURL || item.thumbnailPath || "") : ""; }
  function escapeHtml(value) { return String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;"); }
  function filenameFromItem(item = {}) { const ext = String(item.ext || item.filePath?.split(".").pop() || "png").replace(/^\./, "") || "png"; const rawName = String(item.name || item.filePath?.split(/[\\/]/).pop() || "eagle-image"); const name = rawName.toLowerCase().endsWith("." + ext.toLowerCase()) ? rawName.slice(0, -(ext.length + 1)) : rawName; return `${name || "eagle-image"}.${ext}`; }
  function buildAnalyzePayload(item, bytes) { if (!item?.filePath) throw new Error("当前 Eagle 项目没有可读取的 filePath"); if (!bytes?.length) throw new Error("图片文件为空或读取失败"); const buffer = Buffer.isBuffer(bytes) ? bytes : Buffer.from(bytes); const stableId = String(item.id || Date.now()).replace(/[^a-zA-Z0-9_-]/g, "-"); return { id: `eagle-${stableId}-${Date.now()}`, fileName: filenameFromItem(item), base64Data: buffer.toString("base64"), mimeType: mimeFromPath(item.filePath) }; }
  function firstString(...values) { return values.find((value) => typeof value === "string" && value.trim()) || ""; }
  function promptForItem(item, target, lang) { if (!item) return ""; if (target === "nano") return lang === "zh" ? firstString(item.promptNanoBananaZh, item.promptNanoBananaEn, item.prompt_zh, item.prompt_en) : firstString(item.promptNanoBananaEn, item.promptNanoBananaZh, item.prompt_en, item.prompt_zh); return lang === "zh" ? firstString(item.promptGptImageZh, item.prompt_zh, item.promptGptImageEn, item.prompt_en) : firstString(item.promptGptImageEn, item.prompt_en, item.promptGptImageZh, item.prompt_zh); }
  function normalizeError(error) { const message = error?.message || String(error || "未知错误"); if (/ECONNREFUSED|ENOTFOUND|EHOSTUNREACH|Failed to fetch|NetworkError|fetch failed|socket hang up/i.test(message)) return "无法连接 EKO 本地软件。请先打开 EKO，并确认设置中心的 API 可用后重试。"; if (/timeout|timed out|aborted/i.test(message)) return "连接 EKO 本地软件超时。请确认软件已打开，并稍后重试。"; return message; }
  function resolvePreviewSrc(item) { if (!item) return ""; if (item.thumbnailURL || item.fileURL || item.url) return String(item.thumbnailURL || item.fileURL || item.url); const imagePath = item.thumbnailPath || item.filePath; if (!imagePath || !fs) return ""; try { const bytes = fs.readFileSync(imagePath); return `data:${mimeFromPath(imagePath)};base64,${bytes.toString("base64")}`; } catch (error) { state.error = `预览图读取失败：${normalizeError(error)}`; return ""; } }

  function render() {
    const item = state.selectedItem;
    const prompt = promptForItem(state.resultItem, state.target, state.lang);
    const app = $("#app");
    if (!app) return;
    app.innerHTML = `
      <section class="panel">
        <header class="header"><div><h1>EKO 图片反推</h1><p>${item ? escapeHtml(item.name || item.filePath || "已选择图片") : "在 Eagle 中选择一张图片"}</p></div><button class="icon-button" id="refreshButton" title="刷新选择">↻</button></header>
        ${state.previewSrc ? `<img class="preview" src="${escapeHtml(state.previewSrc)}" alt="" />` : `<div class="empty-preview">未读取到预览图</div>`}
        <div class="actions"><button class="primary" id="analyzeButton" ${state.busy || !item ? "disabled" : ""}>${state.busy ? "分析中..." : "反推这张图"}</button><button id="healthButton" ${state.busy ? "disabled" : ""}>检查 EKO</button></div>
        <p class="status ${state.error ? "is-error" : ""}">${escapeHtml(state.error || state.status)}</p>
        ${state.resultItem ? `<div class="tabs model-tabs"><button data-target="gpt" class="${state.target === "gpt" ? "active" : ""}">GPT Image</button><button data-target="nano" class="${state.target === "nano" ? "active" : ""}">Nano Banana</button></div><div class="tabs lang-tabs"><button data-lang="zh" class="${state.lang === "zh" ? "active" : ""}">中文</button><button data-lang="en" class="${state.lang === "en" ? "active" : ""}">English</button></div><label class="prompt-label">${state.target === "nano" ? "Nano Banana" : "GPT Image"} · ${state.lang === "zh" ? "中文 Prompt" : "English Prompt"}</label><textarea readonly id="promptText">${escapeHtml(prompt)}</textarea><button class="copy" id="copyButton">复制当前 Prompt</button>` : ""}
      </section>`;
    bindEvents();
  }

  function bindEvents() { $("#refreshButton")?.addEventListener("click", () => refreshSelection({ force: true })); $("#healthButton")?.addEventListener("click", checkHealthWithUi); $("#analyzeButton")?.addEventListener("click", analyzeSelected); document.querySelectorAll("[data-target]").forEach((button) => button.addEventListener("click", () => { state.target = button.dataset.target; render(); })); document.querySelectorAll("[data-lang]").forEach((button) => button.addEventListener("click", () => { state.lang = button.dataset.lang; render(); })); $("#copyButton")?.addEventListener("click", copyPrompt); }

  async function refreshSelection(options = {}) { const silent = Boolean(options.silent); if (!silent) state.error = ""; try { const selected = await eagle.item.getSelected(); const nextItem = Array.isArray(selected) ? selected[0] : selected; const nextKey = selectedItemKey(nextItem); const changed = nextKey !== state.selectionKey; if (!changed && silent && !options.force) return; state.selectedItem = nextItem || null; state.selectionKey = nextKey; state.previewSrc = resolvePreviewSrc(state.selectedItem); if (changed) { state.resultItem = null; if (!state.error) state.status = state.selectedItem ? "已选择图片，可开始反推" : "请选择一张图片"; } render(); } catch (error) { if (!silent) { state.error = normalizeError(error); render(); } } }
  function startSelectionWatcher() { if (state.selectionTimer) clearInterval(state.selectionTimer); state.selectionTimer = setInterval(() => { if (!state.busy && window.eagle?.item?.getSelected) refreshSelection({ silent: true }); }, 500); if (state.warmupTimer) clearInterval(state.warmupTimer); let warmupTicks = 0; state.warmupTimer = setInterval(() => { warmupTicks += 1; if (!state.busy && window.eagle?.item?.getSelected) refreshSelection({ silent: true, force: true }); if (warmupTicks >= 24 || state.selectedItem) { clearInterval(state.warmupTimer); state.warmupTimer = null; } }, 250); window.addEventListener("focus", () => refreshSelection({ silent: true, force: true })); document.addEventListener("visibilitychange", () => { if (!document.hidden) refreshSelection({ silent: true, force: true }); }); if (window.eagle?.onPluginShow) eagle.onPluginShow(() => refreshSelection({ silent: true, force: true })); }
  function requestJson(method, path, body) { return new Promise((resolve, reject) => { if (!http) return reject(new Error("Eagle 插件无法访问 Node http 模块")); const payload = body ? Buffer.from(JSON.stringify(body), "utf8") : null; const req = http.request({ hostname: "127.0.0.1", port: 17621, path, method, headers: payload ? { "Content-Type": "application/json", "Content-Length": payload.length } : {}, timeout: method === "GET" ? 3000 : 120000 }, (res) => { const chunks = []; res.on("data", (chunk) => chunks.push(chunk)); res.on("end", () => { const text = Buffer.concat(chunks).toString("utf8"); let data = {}; try { data = text ? JSON.parse(text) : {}; } catch { data = { error: text }; } if (res.statusCode < 200 || res.statusCode >= 300 || data.ok === false) reject(new Error(data.error || `EKO 请求失败 (${res.statusCode})`)); else resolve(data); }); }); req.on("timeout", () => req.destroy(new Error("Request timeout"))); req.on("error", reject); if (payload) req.write(payload); req.end(); }); }
  async function checkHealthWithUi() { state.busy = true; state.error = ""; state.status = "正在连接 EKO..."; render(); try { const health = await requestJson("GET", "/health"); state.status = `EKO 已连接 · ${health.version || "unknown"}`; } catch (error) { state.error = normalizeError(error); } finally { state.busy = false; render(); } }
  async function analyzeSelected() { if (!state.selectedItem) return; state.busy = true; state.error = ""; state.status = "正在读取 Eagle 图片..."; render(); try { if (!fs) throw new Error("Eagle 插件无法访问 Node fs 模块"); await requestJson("GET", "/health"); const bytes = fs.readFileSync(state.selectedItem.filePath); state.status = "正在发送到 EKO 分析..."; render(); const payload = buildAnalyzePayload(state.selectedItem, bytes); const response = await requestJson("POST", "/analyze", payload); state.resultItem = response.item; state.target = response.item?.promptNanoBananaZh || response.item?.promptNanoBananaEn ? "nano" : "gpt"; state.status = "已保存到 EKO 历史"; } catch (error) { state.error = normalizeError(error); } finally { state.busy = false; render(); } }
  async function copyPrompt() { const prompt = promptForItem(state.resultItem, state.target, state.lang); if (!prompt) return; await navigator.clipboard.writeText(prompt); state.status = "Prompt 已复制"; render(); }
  async function initializePlugin() { if (state.initialized) { await refreshSelection({ silent: true, force: true }); return; } render(); if (!window.eagle) { state.error = "请在 Eagle 插件环境中打开"; render(); return; } state.initialized = true; try { const theme = await eagle.app.theme; document.body.setAttribute("theme", theme || "dark"); eagle.onThemeChanged?.((nextTheme) => document.body.setAttribute("theme", nextTheme || "dark")); } catch {} await refreshSelection({ force: true }); startSelectionWatcher(); }
  window.addEventListener("DOMContentLoaded", () => { if (window.eagle?.onPluginCreate) eagle.onPluginCreate(initializePlugin); initializePlugin(); });
})();